### ISSUE TITLE
Automated Build on Docker Hub?

### ISSUE THREAD

**Issue by mikljohansson** [SamSaffron/graphite_docker#15]
Great image! We're finding it really useful as a workbench to locally test monitoring for apps.

It'd be extremely helpful if you could setup an automated build on Docker Hub for this project. Then the README could be changed to refer to e.g. "docker run .. samsaffron/graphite" instead of the somewhat outdated "nickstenning/graphite". These days Docker Hub can build directly from github and can use Web Hooks to automate it, some info is available at

 https://docs.docker.com/docker-hub/github/

**Comment by SamSaffron** [comment]
Sounds good, I will have a look into it.

**Comment by jacobbednarz** [comment]
Any progress on this one? I'd like to pull directly from dockerhub instead of building it locally on our infrastructure. If not, any chance we could get an updated version on dockerhub? :D

**Comment by SamSaffron** [comment]
Sure this is now done ... I hope :)

**Comment by jacobbednarz** [comment]
Worked like a charm. 🌟
