### ISSUE TITLE
Missing pytz module is making graphite crash

### ISSUE THREAD

**Issue by erikcw** [SamSaffron/graphite_docker#17]
I noticed that my graphite graphs were crashing with 500 errors (`'LocalTimezone' object has no attribute 'localize'`), and after digging in I found this issue:

https://github.com/graphite-project/graphite-web/issues/1019

Adding `pip install pytz` to the Dockerfile made everything work again.

**Comment by SamSaffron** [comment]
sounds like a fine change, can you do a PR  ?
