### ISSUE TITLE
Google auth "Fill the blanck"

### ISSUE THREAD

**Issue by IVBakker** [SamSaffron/graphite_docker#5]
Hi,

Could you add more details about the google auth:
```
Fill in the blanks in supervisord.conf before building the image, otherwise Google auth will not work. You will need to register an app on google see: https://github.com/bitly/google_auth_proxy for more details
```
I looked at supervisord.conf and I didn't see any obvious blank. I'm also not totally familiar with Docker, how am I supposed to edit this file before running? I also see there is a script file ```start```, what does it do?

I really want to use your docker application because it contains everything I need, but I need more info about it.
Regards

**Comment by heyman** [comment]
I believe the Google auth stuff was removed in https://github.com/SamSaffron/graphite_docker/commit/ed789186f27c899f8150e64ba2513e61fc5c6e5b

I guess it just wasn't removed from the Readme as well.

**Comment by IVBakker** [comment]
Oh cool, thanks. So need to investigate was my problem on my config then
